name: reviewdog
on: [pull_request]

jobs:
  credo:
    name: Credo
    runs-on: ubuntu-latest
    container:
      image: elixir:1.10.3-slim
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: credo
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}

      - name: credo-pr-review
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
